### ISSUE TITLE
include has wrong relative path

### ISSUE THREAD

**Issue by mauro3** [one-more-minute/Requires.jl#2]
The example in the readme using include does not work when the REPL is in another directory than the file where the include happens.  As the test case includes directories I set up a repo for it:
https://github.com/mauro3/requires_bug

Running `runA.jl` which is in `dirA` works, but running the essentially same script `runelsewhere.jl` in the parent directory does not:
```
...julia/issues/requires_bug2(master)  >> cd dirA 
...issues/requires_bug2/dirA(master)  >> julia runA.jl 
before using Jewel
hello
after using Jewel
var1 => 1
...issues/requires_bug2/dirA(master)  >> cd ..
...julia/issues/requires_bug2(master)  >> julia runelsewehere.jl 
before using Jewel
ERROR: could not open file /home/mauro/julia/issues/requires_bug2/fl2.jl
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in anonymous at /home/mauro/.julia/v0.3/Requires/src/require.jl:29
 in anonymous at /home/mauro/.julia/v0.3/Requires/src/require.jl:21
 in map at abstractarray.jl:1328
 in loadmod at /home/mauro/.julia/v0.3/Requires/src/require.jl:20
 in require at /home/mauro/.julia/v0.3/Requires/src/require.jl:9
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/mauro/julia/issues/requires_bug2/runelsewehere.jl, in expression starting on line 3
```

runelsewhere.jl works with the `@require Jewel` removed.

**Comment by one-more-minute** [comment]
Thanks for the really detailed report on this. I *think* it should be as simple as remembering the `:SOURCE_PATH` variable in task local storage when evaluating, so I'll have a go at this when I get a moment.

**Comment by IainNZ** [comment]
I think I also see this, althought I'm not at REPL e.g.

```
module Foo
    using Requires

    @require JuMP include("stuff.jl")

    using Compose
end
using Foo
```

```
ERROR: could not open file /Users/idunning/.julia/v0.3/Compose/src/stuff.jl
...
```

Not sure why its looking there!

**Comment by IainNZ** [comment]
(well, possibly relevant, is that Compose also lazily-loads JuMP)

**Comment by one-more-minute** [comment]
It's been a long time coming, but that should fix this. Let me know if you see any problems with it.
