### ISSUE TITLE
Exports question

### ISSUE THREAD

**Issue by IainNZ** [one-more-minute/Requires.jl#5]
So I have something like this

```julia
module Foo
  @require Compose include("draw.jl")
end
```

`draw.jl` defines a `draw_it()` function. I want to export `draw_it` from `Foo`, but I can't do

```julia
module Foo
  export draw_it
  @require Compose include("draw.jl")
end
```

because `draw_it` doesn't isn't defined apparently. How is this supposed to look?

**Comment by prcastro** [comment]
Same problem here

**Comment by one-more-minute** [comment]
Apologies for the ridiculously late response on this. So firstly, this seems like an odd thing to want to do – normally you would just extend a function in Foo for a method in Compose or vice versa, which for one thing will make sure that it's not possible to call a method before it has been defined. Can you elaborate on your use case?

Exporting a function usually works just fine before the function is defined, so this should work in theory – I'll try and reproduce it locally.

**Comment by one-more-minute** [comment]
```julia
# Foo.jl
module Foo
using Requires
export foo
@require Lazy include("define.jl")
end
```
```julia
# define.jl
foo() = println("hello, world")
```
```julia
julia> include("runelsewehere.jl")

julia> using .Foo

julia> foo()
ERROR: foo not defined

julia> using Lazy

julia> foo()
hello, world
```
I'll close in case it's fixed itself and/or you no longer need it, but let me know if you can still reproduce, it of course.

**Comment by IainNZ** [comment]
Yeah re-reading this I don't really know what I was really getting at here.
