### ISSUE TITLE
Broken for current 0.4?

### ISSUE THREAD

**Issue by timholy** [one-more-minute/Requires.jl#8]
I decided to check this package out. Is it broken by the `require(::Symbol)` change?

A.jl:
```jl
module A

using Requires

export foo, bar

foo(x) = "hello"
@require B begin
    println("defining bar")
    bar(y::B.Btype) = "there"
end

end
```

B.jl:
```jl
module B

export Btype

type Btype
    val::Int
end

end
```

Test:
```jl
julia> using Requires, A

julia> foo(7)
"hello"

julia> using B

julia> bar(7)
ERROR: UndefVarError: bar not defined
```

I'm guessing the `require(::Symbol)` thing is hard to get around?

**Comment by one-more-minute** [comment]
Hmm, looks that way. I think the `require(::Symbol)` change must've gone over my head, any chance I could get a reference for that?

Should be workaroundable either way.

**Comment by timholy** [comment]
That's an immensely clever hack. :smile:

`require(::Symbol)` comes from https://github.com/JuliaLang/julia/pull/12040 and https://github.com/JuliaLang/julia/pull/8745.

**Comment by one-more-minute** [comment]
It'll take a bit more of a challenge to make me deprecate this package :) Thanks for the link!
